contact_links:
  - name: ⚠️ Application issue
    url: https://github.com/Anipacaorg/Anipaca/issues/new/choose
    about: Issues and requests about the app itself should be opened in the Anipaca repository instead
  - name: 📦 Anipaca extensions
    url: https://Anipaca.org/extensions
    about: List of all available extensions with download links
  - name: 🖥️ Anipaca website
    url: https://Anipaca.org/help/
    about: Guides, troubleshooting, and answers to common questions
